//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDIFACTApp.PayloadServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PayloadContract", Namespace="http://schemas.datacontract.org/2004/07/PayloadService")]
    [System.SerializableAttribute()]
    public partial class PayloadContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommandStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SiteStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ValidXMLField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CommandStatus {
            get {
                return this.CommandStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.CommandStatusField, value) != true)) {
                    this.CommandStatusField = value;
                    this.RaisePropertyChanged("CommandStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SiteStatus {
            get {
                return this.SiteStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.SiteStatusField, value) != true)) {
                    this.SiteStatusField = value;
                    this.RaisePropertyChanged("SiteStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ValidXML {
            get {
                return this.ValidXMLField;
            }
            set {
                if ((this.ValidXMLField.Equals(value) != true)) {
                    this.ValidXMLField = value;
                    this.RaisePropertyChanged("ValidXML");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PayloadServiceReference.IPayloadService")]
    public interface IPayloadService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPayloadService/PostPayloadXML", ReplyAction="http://tempuri.org/IPayloadService/PostPayloadXMLResponse")]
        EDIFACTApp.PayloadServiceReference.PayloadContract PostPayloadXML(string xmlData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPayloadService/PostPayloadXML", ReplyAction="http://tempuri.org/IPayloadService/PostPayloadXMLResponse")]
        System.Threading.Tasks.Task<EDIFACTApp.PayloadServiceReference.PayloadContract> PostPayloadXMLAsync(string xmlData);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPayloadServiceChannel : EDIFACTApp.PayloadServiceReference.IPayloadService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PayloadServiceClient : System.ServiceModel.ClientBase<EDIFACTApp.PayloadServiceReference.IPayloadService>, EDIFACTApp.PayloadServiceReference.IPayloadService {
        
        public PayloadServiceClient() {
        }
        
        public PayloadServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PayloadServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PayloadServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PayloadServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public EDIFACTApp.PayloadServiceReference.PayloadContract PostPayloadXML(string xmlData) {
            return base.Channel.PostPayloadXML(xmlData);
        }
        
        public System.Threading.Tasks.Task<EDIFACTApp.PayloadServiceReference.PayloadContract> PostPayloadXMLAsync(string xmlData) {
            return base.Channel.PostPayloadXMLAsync(xmlData);
        }
    }
}
